server:
  port: 9004
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10086/eureka/
spring:
  application:
    name: feign
MEMBER:  #服务名   配置负载均衡策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true  #开启服务降级